export const LANG_DISPLAY: Record<string, string> = {
  javascript: 'JavaScript', js: 'JavaScript', jsx: 'JavaScript JSX',
  typescript: 'TypeScript', ts: 'TypeScript', tsx: 'TypeScript TSX',
  python: 'Python', py: 'Python',
  java: 'Java',
  cpp: 'C++',
  c: 'C',
  csharp: 'C#', cs: 'C#',
  go: 'Go',
  rust: 'Rust', rs: 'Rust',
  swift: 'Swift',
  kotlin: 'Kotlin', kt: 'Kotlin',
  dart: 'Dart',
  ruby: 'Ruby', rb: 'Ruby',
  php: 'PHP',
  scala: 'Scala',
  haskell: 'Haskell', hs: 'Haskell',
  lua: 'Lua',
  sql: 'SQL',
  css: 'CSS',
  html: 'HTML',
  bash: 'Bash', shell: 'Shell', sh: 'Shell',
  powershell: 'PowerShell', ps1: 'PowerShell',
  json: 'JSON',
  yaml: 'YAML', yml: 'YAML',
  xml: 'XML',
  markdown: 'Markdown', md: 'Markdown', mdx: 'MDX',
  latex: 'LaTeX', tex: 'LaTeX',
  r: 'R',
  dockerfile: 'Dockerfile', docker: 'Dockerfile',
  graphql: 'GraphQL', gql: 'GraphQL',
  ini: 'INI',
  toml: 'TOML',
  makefile: 'Makefile', make: 'Makefile',
  nginx: 'Nginx',
  diff: 'Diff',
  viml: 'Vim Script', vim: 'Vim Script', vimscript: 'Vim Script',
  text: 'Text', plaintext: 'Text',
  elixir: 'Elixir', ex: 'Elixir',
  clojure: 'Clojure', clj: 'Clojure',
  groovy: 'Groovy',
  objectivec: 'Objective-C', objc: 'Objective-C',
  perl: 'Perl',
  raku: 'Raku',
  zig: 'Zig',
  terraform: 'Terraform', tf: 'Terraform',
  solidity: 'Solidity',
  svelte: 'Svelte',
  vue: 'Vue',
  prisma: 'Prisma',
  cmake: 'CMake',
}

export function langDisplay(id: string): string {
  return LANG_DISPLAY[id] || id
}

export const LANG_ICONS: Record<string, string> = {
  javascript: 'vscode-icons:file-type-js-official',
  typescript: 'vscode-icons:file-type-typescript-official',
  python: 'vscode-icons:file-type-python',
  java: 'vscode-icons:file-type-java',
  cpp: 'vscode-icons:file-type-cpp3',
  c: 'vscode-icons:file-type-c',
  csharp: 'vscode-icons:file-type-csharp',
  go: 'vscode-icons:file-type-go',
  rust: 'vscode-icons:file-type-rust',
  swift: 'vscode-icons:file-type-swift',
  kotlin: 'vscode-icons:file-type-kotlin',
  dart: 'vscode-icons:file-type-dartlang',
  ruby: 'devicon:ruby',
  php: 'devicon:php',
  scala: 'devicon:scala',
  haskell: 'devicon:haskell',
  lua: 'devicon:lua',
  sql: 'vscode-icons:file-type-sql',
  css: 'vscode-icons:file-type-css',
  html: 'vscode-icons:file-type-html',
  bash: 'vscode-icons:file-type-shell',
  powershell: 'vscode-icons:file-type-powershell',
  json: 'vscode-icons:file-type-json',
  yaml: 'vscode-icons:file-type-yaml',
  xml: 'vscode-icons:file-type-xml',
  markdown: 'vscode-icons:file-type-markdown',
  latex: 'vscode-icons:file-type-tex',
  r: 'devicon:r',
  dockerfile: 'devicon:docker',
  graphql: 'vscode-icons:file-type-graphql',
  ini: 'vscode-icons:file-type-config',
  toml: 'vscode-icons:file-type-toml',
  makefile: 'vscode-icons:file-type-makefile',
  nginx: 'vscode-icons:file-type-nginx',
  diff: 'vscode-icons:file-type-diff',
  viml: 'devicon:vim',
  elixir: 'devicon:elixir',
  clojure: 'devicon:clojure',
  groovy: 'devicon:groovy',
  perl: 'devicon:perl',
  erlang: 'devicon:erlang',
  objectivec: 'vscode-icons:file-type-objectivec',
}